### ISSUE TITLE
Possible extension to LLM

### ISSUE THREAD

**Issue by ywen666** [alstonlo/torch-influence#10]
I bumped into the awesome new paper Studying Large Language Model Generalization with Influence Functions (https://arxiv.org/pdf/2308.03296.pdf).

Just wondering if it is possible to extend this framework to reproduce some experiments in this paper. If it is possible, what are the rough steps to implement the Eq 25 and Eq 26 in this repo?

**Comment by pomonam** [comment]
Thank you for the comment! I recently released the code for the paper in this repo: https://github.com/pomonam/kronfluence. I hope this helps!
