### ISSUE TITLE
Could's find 'dataset_dog-fish_embeds.npz' file at CodaLab

### ISSUE THREAD

**Issue by Hongbo-Z** [alstonlo/torch-influence#11]
Hi,

Thanks for sharing this code, I met a problem when I checked  examples/analyze_dogfish.py. 

 line 22: DOGFISH_EMB_PATH = BASE_DIR / "dataset_dog-fish_embeds.npz" 

As I couldn't find **_dataset_dog-fish_embeds.npz_** at the [link ](https://worksheets.codalab.org/bundles/0x550cd344825049bdbb865b887381823c)you offered.

Is there any typo of dataset_dog-fish_embeds.npz which should be [dataset_koda.npz](https://worksheets.codalab.org/rest/bundles/0x550cd344825049bdbb865b887381823c/contents/blob/dataset_koda.npz) instead?

Thanks in advance!

**Comment by alstonlo** [comment]
It should be okay if the file does not exist, since it should be generated by `analyze_dogfish.py` ([here](https://github.com/alstonlo/torch-influence/blob/main/examples/analyze_dogfish.py#L68)). Only the `dataset_dog-fish_train-900_test-300.npz` file needs to be downloaded from CodaLab!

**Comment by Hongbo-Z** [comment]
> It should be okay if the file does not exist, since it should be generated by `analyze_dogfish.py` ([here](https://github.com/alstonlo/torch-influence/blob/main/examples/analyze_dogfish.py#L68)). Only the `dataset_dog-fish_train-900_test-300.npz` file needs to be downloaded from CodaLab!

Yes, you are right, what we need to download is just the  `dataset_dog-fish_train-900_test-300.npz` file.

Thanks for your quick response. 😄
