### ISSUE TITLE
Scale selection for LiSSA

### ISSUE THREAD

**Issue by I-Good-Vegetable** [alstonlo/torch-influence#12]
Hi,

I'm wondering the parameter selection for LiSSA, especially for the scale param.

Many thanks indeed!

**Comment by pomonam** [comment]
Thank you for the question! For the scale selection, one should try several values (e.g., [1, 10, 100, 1000, 10,000, ...]) and select the smallest one that the iHVP does not diverge (you can check the norm of the iHVP at each iteration to determine if it is converging or diverging).
