### ISSUE TITLE
Should influence scores take the inverse

### ISSUE THREAD

**Issue by I-Good-Vegetable** [alstonlo/torch-influence#13]
Hi,

I notice that the influence scores = stest @ training sample gradient; however the original influence function is - stest @ training sample gradient. I'm wondering it is intentionally implemented like this? (Maybe I'm wrong)

Many thanks

**Comment by alstonlo** [comment]
I believe this is intentional. Our [docs](https://torch-influence.readthedocs.io/en/latest/#torch_influence.BaseInfluenceModule.influences) specify what is being computed by the `influences()` function!

**Comment by I-Good-Vegetable** [comment]
Thanks a lot!

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: alstonlo ***@***.***>
发送时间: Sunday, January 14, 2024 1:57:29 AM
收件人: alstonlo/torch-influence ***@***.***>
抄送: Jason ***@***.***>; Author ***@***.***>
主题: Re: [alstonlo/torch-influence] Should influence scores take the inverse (Issue #13)


I believe this is intentional. Our docs<https://torch-influence.readthedocs.io/en/latest/#torch_influence.BaseInfluenceModule.influences> specify what is being computed by the influences() function!

―
