### ISSUE TITLE
Can I use this framework if the network is trained with AdamW

### ISSUE THREAD

**Issue by I-Good-Vegetable** [alstonlo/torch-influence#14]

**Comment by I-Good-Vegetable** [comment]
Hi,

I'm wondering whether I can invoke this framework if I trained my network with AdamW optimizer? Many thanks

**Comment by pomonam** [comment]
Yes, since the formulation of influence functions is based on the Implicit Function Theorem, it does not take into consideration the type of optimizer used.

**Comment by I-Good-Vegetable** [comment]
Got it! Thank you very much Dr Bae for the answers and your patience!
