### ISSUE TITLE
Why does LiSSA need a test loader?

### ISSUE THREAD

**Issue by gumityolcu** [alstonlo/torch-influence#15]
Hello,

Why does LiSSA need a test dataloader in the constructor?

I want to get influence values for a single sample, do i have to initialize the module for each new sample? Is there a straightforward way to initialize the object and use it with different test data?

Thanks,
Galip

**Comment by pomonam** [comment]
Thank you for raising the issue. One way is to create a test dataloader with all your samples and run influences for a single sample by specifying `test_idxs` (for example, 0 if you want to compute influence values for the first sample). You can also initialize the new object each time to run influences on a new test dataloader. We also recently released influence function computation with EK-FAC (https://github.com/pomonam/kronfluence), which should better handle this (although this does not have LiSSA implementation). 

Please let me know if you have other questions.

**Comment by gumityolcu** [comment]
Thank you for the quick and clear response! Closing issue since this is resolved. I will open new issues if I have further confusions or questions.
