### ISSUE TITLE
Restriction of considered parameters

### ISSUE THREAD

**Issue by gumityolcu** [alstonlo/torch-influence#16]
Hello,

I am trying to restrict the computations to only use the final layer parameters. Is it enough to override the _model_params() of the BaseInfluenceModule, or do I need to do further modifications.

I am asking to be sure, because it takes a long time to generate influence scores.

Thank you!

**Comment by pomonam** [comment]
Yes, as you mentioned, overwriting the code or setting `param.requires_grad = False` to other parameters should be able to compute influence on only specific parameters (e.g., final layer parameters). Setting `param.requires_grad = False` can be more efficient.

**Comment by gumityolcu** [comment]
Thanks for the quick responses
