### ISSUE TITLE
cudnn RNN backward can only be called in training mode

### ISSUE THREAD

**Issue by yzhang511** [alstonlo/torch-influence#7]
Hi, thank you for developing this package; it has proven incredibly useful for my ongoing project. I've encountered an issue while working with GPU. Specifically, I'm attempting to compute influences using an LSTM model. Interestingly, when using the CPU, everything runs seamlessly. However, upon switching to GPU, I encountered the following error message:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-61-99d9acc8245f>](https://localhost:8080/#) in <cell line: 4>()
      3 all_train_idxs = list(range(X_train.shape[0]))
      4 for test_idx in tqdm(test_idxs, desc="Computing Influences"):
----> 5     influences = module.influences(train_idxs=all_train_idxs, test_idxs=[test_idx[0]])
      6     saved_influences.append(influences)
      7 

5 frames
[/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py](https://localhost:8080/#) in grad(outputs, inputs, grad_outputs, retain_graph, create_graph, only_inputs, allow_unused, is_grads_batched)
    301         return _vmap_internals._vmap(vjp, 0, 0, allow_none_pass_through=True)(grad_outputs_)
    302     else:
--> 303         return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    304             t_outputs, grad_outputs_, retain_graph, create_graph, t_inputs,
    305             allow_unused, accumulate_grad=False)  # Calls into the C++ engine to run the backward pass

RuntimeError: cudnn RNN backward can only be called in training mode
```
I believe this issue might affect others who are utilizing RNN on a GPU. Could you please help me resolve this issue? Thank you!

**Comment by alstonlo** [comment]
Thank you for the kind words! 

We think that the issue arises from setting the model to evaluation mode when the influence module is initialized ([L144 of `base.py`](https://github.com/alstonlo/torch-influence/blob/8b4f0756acf642a38a8b24a517da89343a9de7d0/torch_influence/base.py#L144)). Following some related [discussion](https://discuss.pytorch.org/t/when-should-we-set-torch-backends-cudnn-enabled-to-false-especially-for-lstm/106571) on the PyTorch forums, some possible workarounds could be to:
- Call `train()` on the RNN layers after the influence module is initialized 
- Set `torch.backends.cudnn.enabled = False`

**Comment by pomonam** [comment]
Closing for now; please feel free to re-open if the issue does not get solved.
