### ISSUE TITLE
Official Implementation of PBRF

### ISSUE THREAD

**Issue by Hzfinfdu** [alstonlo/torch-influence#8]
Thanks for your wonderful work **If Influence Functions are the Answer, Then What is the Question?**.

I had trouble reimplementing PBRF on MNIST+MLP since I found that the initial loss can be quite small and unstable in optimization. Besides, I am not quite sure whether my implementation is true. Could you please help me out or release the code of PBRF?

Thanks in advance!

**Comment by pomonam** [comment]
Please see https://github.com/pomonam/jax-influence/issues/1
