### ISSUE TITLE
how to set parameters for LiSSAInfluenceModule?

### ISSUE THREAD

**Issue by rguo12** [alstonlo/torch-influence#9]
Hi,

Thanks for sharing the code.

For the **LiSSAInfluenceModule**, I could not find any example for it.
Specifically, I wonder what are recommended values for
depth (int) – the recurrence depth 
scale (float) – the scaling factor
for widely used datasets like CIFAR-10, CIFAR-100 and ImageNet.

Best,

RC

**Comment by gyh-ustc** [comment]
Hi, I have the same question as yours. And I also found that  LiSSAInfluenceModule return a list of [nan]. Do you know why? Thank you.

**Comment by Hongbo-Z** [comment]
Normally (the recurrence depth)*(the number of repetition)=number of traning dataset.

**Comment by ValentinaMiller** [comment]
Hi, did anyone get any further on this question?

**Comment by pomonam** [comment]
Sorry for the late reply. Yes, we should generally set `depth x repetition = num_train` as @Hongbo-Z mentioned. I recommend setting `repetition=1` and `depth=num_train` for generic hyperparameters, but ideally, for each task, one should monitor the norm of the IHVP and terminate when the norm seems to converge.
